Traceback (most recent call last):
  File "/home/uncoder/my_books/sm6-cookbook/.venv/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/uncoder/my_books/sm6-cookbook/.venv/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/uncoder/my_books/sm6-cookbook/.venv/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/uncoder/my_books/sm6-cookbook/.venv/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/uncoder/my_books/sm6-cookbook/.venv/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/uncoder/my_books/sm6-cookbook/.venv/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
with plt.style.context("seaborn-poster"):
    fig, ax = plt.subplots()
    ax.plot(x, y, label="Функция $f(x)$")
    ax.plot(x, y_der, label="Производная $f'(x)$")
    ax.plot(x, y_der2, label="Производная $f''(x)$")
    ax.set(
        xlabel="$x$",
        ylabel="$y$",
        title="Функция $f(x) = x^3$ и её производные"
    )
    ax.legend()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
File [0;32m~/my_books/sm6-cookbook/.venv/lib/python3.10/site-packages/matplotlib/style/core.py:137[0m, in [0;36muse[0;34m(style)[0m
[1;32m    136[0m [38;5;28;01mtry[39;00m:
[0;32m--> 137[0m     style [38;5;241m=[39m [43m_rc_params_in_file[49m[43m([49m[43mstyle[49m[43m)[49m
[1;32m    138[0m [38;5;28;01mexcept[39;00m [38;5;167;01mOSError[39;00m [38;5;28;01mas[39;00m err:

File [0;32m~/my_books/sm6-cookbook/.venv/lib/python3.10/site-packages/matplotlib/__init__.py:866[0m, in [0;36m_rc_params_in_file[0;34m(fname, transform, fail_on_error)[0m
[1;32m    865[0m rc_temp [38;5;241m=[39m {}
[0;32m--> 866[0m [38;5;28;01mwith[39;00m _open_file_or_url(fname) [38;5;28;01mas[39;00m fd:
[1;32m    867[0m     [38;5;28;01mtry[39;00m:

File [0;32m/usr/lib/python3.10/contextlib.py:135[0m, in [0;36m_GeneratorContextManager.__enter__[0;34m(self)[0m
[1;32m    134[0m [38;5;28;01mtry[39;00m:
[0;32m--> 135[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mnext[39;49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mgen[49m[43m)[49m
[1;32m    136[0m [38;5;28;01mexcept[39;00m [38;5;167;01mStopIteration[39;00m:

File [0;32m~/my_books/sm6-cookbook/.venv/lib/python3.10/site-packages/matplotlib/__init__.py:843[0m, in [0;36m_open_file_or_url[0;34m(fname)[0m
[1;32m    842[0m fname [38;5;241m=[39m os[38;5;241m.[39mpath[38;5;241m.[39mexpanduser(fname)
[0;32m--> 843[0m [38;5;28;01mwith[39;00m [38;5;28;43mopen[39;49m[43m([49m[43mfname[49m[43m,[49m[43m [49m[43mencoding[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43mutf-8[39;49m[38;5;124;43m'[39;49m[43m)[49m [38;5;28;01mas[39;00m f:
[1;32m    844[0m     [38;5;28;01myield[39;00m f

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'seaborn-poster'

The above exception was the direct cause of the following exception:

[0;31mOSError[0m                                   Traceback (most recent call last)
Cell [0;32mIn[20], line 1[0m
[0;32m----> 1[0m [38;5;28;01mwith[39;00m plt[38;5;241m.[39mstyle[38;5;241m.[39mcontext([38;5;124m"[39m[38;5;124mseaborn-poster[39m[38;5;124m"[39m):
[1;32m      2[0m     fig, ax [38;5;241m=[39m plt[38;5;241m.[39msubplots()
[1;32m      3[0m     ax[38;5;241m.[39mplot(x, y, label[38;5;241m=[39m[38;5;124m"[39m[38;5;124mФункция $f(x)$[39m[38;5;124m"[39m)

File [0;32m/usr/lib/python3.10/contextlib.py:135[0m, in [0;36m_GeneratorContextManager.__enter__[0;34m(self)[0m
[1;32m    133[0m [38;5;28;01mdel[39;00m [38;5;28mself[39m[38;5;241m.[39margs, [38;5;28mself[39m[38;5;241m.[39mkwds, [38;5;28mself[39m[38;5;241m.[39mfunc
[1;32m    134[0m [38;5;28;01mtry[39;00m:
[0;32m--> 135[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mnext[39;49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mgen[49m[43m)[49m
[1;32m    136[0m [38;5;28;01mexcept[39;00m [38;5;167;01mStopIteration[39;00m:
[1;32m    137[0m     [38;5;28;01mraise[39;00m [38;5;167;01mRuntimeError[39;00m([38;5;124m"[39m[38;5;124mgenerator didn[39m[38;5;124m'[39m[38;5;124mt yield[39m[38;5;124m"[39m) [38;5;28;01mfrom[39;00m [38;5;28;01mNone[39;00m

File [0;32m~/my_books/sm6-cookbook/.venv/lib/python3.10/site-packages/matplotlib/style/core.py:194[0m, in [0;36mcontext[0;34m(style, after_reset)[0m
[1;32m    192[0m [38;5;28;01mif[39;00m after_reset:
[1;32m    193[0m     mpl[38;5;241m.[39mrcdefaults()
[0;32m--> 194[0m [43muse[49m[43m([49m[43mstyle[49m[43m)[49m
[1;32m    195[0m [38;5;28;01myield[39;00m

File [0;32m~/my_books/sm6-cookbook/.venv/lib/python3.10/site-packages/matplotlib/style/core.py:139[0m, in [0;36muse[0;34m(style)[0m
[1;32m    137[0m         style [38;5;241m=[39m _rc_params_in_file(style)
[1;32m    138[0m     [38;5;28;01mexcept[39;00m [38;5;167;01mOSError[39;00m [38;5;28;01mas[39;00m err:
[0;32m--> 139[0m         [38;5;28;01mraise[39;00m [38;5;167;01mOSError[39;00m(
[1;32m    140[0m             [38;5;124mf[39m[38;5;124m"[39m[38;5;132;01m{[39;00mstyle[38;5;132;01m!r}[39;00m[38;5;124m is not a valid package style, path of style [39m[38;5;124m"[39m
[1;32m    141[0m             [38;5;124mf[39m[38;5;124m"[39m[38;5;124mfile, URL of style file, or library style name (library [39m[38;5;124m"[39m
[1;32m    142[0m             [38;5;124mf[39m[38;5;124m"[39m[38;5;124mstyles are listed in `style.available`)[39m[38;5;124m"[39m) [38;5;28;01mfrom[39;00m [38;5;21;01merr[39;00m
[1;32m    143[0m filtered [38;5;241m=[39m {}
[1;32m    144[0m [38;5;28;01mfor[39;00m k [38;5;129;01min[39;00m style:  [38;5;66;03m# don't trigger RcParams.__getitem__('backend')[39;00m

[0;31mOSError[0m: 'seaborn-poster' is not a valid package style, path of style file, URL of style file, or library style name (library styles are listed in `style.available`)

